---
- name: Set Hostname
  hosts: all
  become: true
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

- name: Apply the PostgreSQL role
  hosts: postgres
  become: true
  vars_files:
    - group_vars/postgres.yaml
  roles:
    - postgres

- name: Apply regiond role
  hosts: regiond
  become: true
  vars_files:
    - group_vars/regiond.yaml
  roles:
    - regiond

- name: Apply rackd role
  hosts: rackd
  become: true
  vars_files:
    - group_vars/rackd.yaml
  roles:
    - rackd

- name: Apply rack+region role
  hosts: regiond_rackd
  become: true
  vars_files:
    - group_vars/regiond_rackd.yaml
  roles:
    - region_rackd
