postgres_version: 14
postgres_config_dir: /etc/postgresql/{{ postgres_version }}/main
postgres_data_dir: /var/lib/postgresql/{{ postgres_version }}/main
postgres_listen_addresses: "*"
postgres_port: 5432
postgres_db_name: maasdb
postgres_db_user: maas
postgres_db_pass: maas
