---
# handlers file for postgres
- name: Reload PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: reloaded

- name: Restart PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted
