---
# tasks file for region + rackd
- name: Install Maas Controller with snap
  community.general.snap:
    name: maas
    classic: true
    state: present
    channel: "{{ regiond_rackd_vars.maas.channel }}"

- name: Check if maas is initialized
  ansible.builtin.command: >
    maas status
  register: maas_status
  failed_when: false

- name: Initialize Maas Region + Rack Controller
  ansible.builtin.command: >
    maas init region+rack
    --database-uri
    postgres://{{ regiond_rackd_vars.db.user }}:{{ regiond_rackd_vars.db.password }}@{{ regiond_rackd_vars.db.address }}:{{ regiond_rackd_vars.db.port }}/{{ regiond_rackd_vars.db.name }}
    --maas-url http://{{ inventory_hostname }}:5240/MAAS
  become: true
  when: maas_status.rc != 0
  notify: Create user for maas
