---
# tasks file for rackd

- name: Install Maas Rackd Controller with snap
  community.general.snap:
    name: maas
    classic: true
    state: present
    channel: "{{ regiond_vars.maas.channel }}"

- name: Synchronize Secret for Maas Rack Controller
  ansible.builtin.synchronize:
    src: "/var/snap/maas/common/maas/secret"
    dest: /tmp/maas-secret
  delegate_to: "{{ groups['regiond'][0] }}"

- name: Initialize Maas Rack Controller
  ansible.builtin.command: >
    maas init rack
    --maas-url http://{{ inventory_hostname }}:5240/MAAS
    --secret $(cat /tmp/maas-secret)"
  become: true
  args:
    creates: /var/snap/maas/current/rackd.conf
