---
# defaults file for postgres
pg_vars:
  version: 16
  locale: en_US.UTF-8
  encoding: UTF8
  hba_file: /etc/postgresql/16/main/pg_hba.conf
  config_dir: /etc/postgresql/16/main
  data_dir: /var/lib/postgresql/16/main
  log_dir: /var/log/postgresql
  service_name: postgresql
  service_state: started
  service_enabled: true
  postgres_db_user: postgres
  options:
    - name: listen_addresses
      value: "localhost"
    - name: log_connections
      value: "on"
    - name: port
      value: "5432"
  users:
    - name: "{{ maas_db_user }}"
      password: "{{ maas_db_password }}"
  dbs:
    - name: "{{ maas_db_name }}"
      owner: "{{ maas_db_user }}"
  privs:
    - db: "{{ maas_db_name }}"
      privs: ALL
      user: "{{ maas_db_user }}"
      type: database
  hba_entries:
    - database: all
      contype: local
      user: all
      method: trust
    - database: "{{ maas_db_name }}"
      contype: local
      user: "{{ maas_db_user }}"
      method: trust
